---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop reactjs-app
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm reactjs-app
    ignore_errors: yes
# Make sure to change the image name with your personal dockerhub account and reposiroty   
  - name: remove used image
    command: docker rmi hosnikadour/frontend-app-iteslab
    ignore_errors: yes
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: build docker image from dockerfile
    command: docker build -t hosnikadour/frontend-app-iteslab .  
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: push image to dockerhub
    command: docker push hosnikadour/frontend-app-iteslab
  - name: run container
    command: docker run -d --restart=always --name reactjs-app -p 3000:80 hosnikadour/frontend-app-iteslab