apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-app
  labels:
    app: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  react-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  react-app
        image:  hosnikadour/frontend-app-iteslab:latest
        ports:
        - containerPort:  3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: default
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80