kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: client-app
        image: "hosnikadour/frontend-app-iteslab:latest"
        imagePullPolicy: Always
        resources:
         #cpu and memory limit
          limits:
            memory: "550Mi"
            cpu: "500m"
        ports: 
         - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: client-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
  