kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - image: hosnikadour/frontend-app-iteslab:latest
        name: client-app
        imagePullPolicy: Always
      containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-service
  namespace: default
spec:

selector:
    app: client-app
    type: LoadBalancer
    ports:
    - name: http
    targetPort: 3000
    port: 80